- setup/docker/01_setup_enketo.bash
I tested this and could not see any ill effects from removing the second `grunt` call.
For my reference, this makes some progress toward resolving kobotoolbox/tasks#140.
> Run `grunt` only once at Docker container start

- setup/docker/create_config.py
Keeping the order of `config.json` consistent from one run to the next helps to
avoid unnecessary `grunt` builds. Fixes #99.
Includes a few changes to remove extraneous whitespace.
> Sort keys when writing JSON in `create_config.py`

- .github/workflows/docker-hub.yml
…using GitHub Actions. For each tag pushed to GitHub, a Docker image is built
and published to https://hub.docker.com/r/kobotoolbox/enketo-express.
I've added the referenced secrets to https://github.com/enketo/enketo-express/settings/secrets.
> added: automated Docker Hub builds

- CHANGELOG.md
- setup/docker/create_config.py
When `encryption key` is not present in `config.json`, a script at start-up generates a new one and injects it into the configuration file under `linked form and data server`.
According to the code, it should be at root level.
- https://github.com/enketo/enketo-express/blob/master/app/controllers/authentication-controller.js#L82
- https://github.com/enketo/enketo-express/blob/master/app/models/user-model.js#L24
> Generate encryption key at the root level of config.json if it does not exist.

- CHANGELOG.md
- app/controllers/api-v1-controller.js
- app/controllers/api-v2-controller.js
- app/controllers/transformation-controller.js
- app/models/cache-model.js
- app/models/survey-model.js
- test/server/api-controller.spec.js
The quota mechanism expects linked server URLs to be specified and cannot do any meaningful checking when they are not.
Skipping these checks also avoids some `keys` queries that can leave the Redis server stuck consuming 100% of CPU and unable to serve other requests.
> changed: skip quota checks for empty server URLs

- tutorials/10-configure.md
It didn't feel immediately clear that the parameter is passed to all OpenRosa requests. I feel like leading with "For most form servers this item does nothing" isn't necessary but if you think I lost something important let me know!
> Clarify query parameter description

- public/js/src/module/connection.js
- tutorials/10-configure.md
Closes #187
Notes on behavior:
- A submission can be divided in batches. The `__csrf` form data field will be added to each batch's `POST`.
- If a readable `__csrf` cookie exists, **regardless of auth type**, Enketo will include a `__csrf` form data field in the submission.
I was initially intending to only look for the cookie field if cookie auth was configured. But it seems to me like the check isn't necessary because if the data server doesn't know anything about this feature it just won't send the `__csrf` cookie so it won't be there for the client to see. It seems vanishingly unlikely that a data server would set a `__csrf` cookie field but then be unable to handle `__csrf` in the submission `POST`.
I verified this by running Enketo and Central locally with Enketo using local Central …
> Read csrf token if it exists and add to submission

- public/js/src/module/settings.js
Closes #195 
This is a less risky approach than #196 which entirely removes this code block.
I manually tried `preview` and `single` prefixes.
> Identify form type prefix when Enketo at subpath

- app/controllers/survey-controller.js
- public/js/src/module/controller-webform.js
Closes #199 
Forgive me, @MartijnR, I looked around for other subpath issues when addressing #195 but didn't spot these. I didn't realize that all that is required to try running as a subpath is to change the config so I hadn't previously tried it locally.
I think the `path` filter on the `once` cookie is a good thing because it means the cookie won't show up in a browser inspector unless a user is at a `single/` path. That makes identifying the cookie and working around it a little bit trickier.
Now I've done the following:
- Tried both `/single` and `/single/once` URLs at a subpath
- Run `grunt eslint`
- Searched across the codebase for `.redirect` and `path=`
I also considered using a relative path for that (`../thanks`) but using the base URL seems more robust. I think it would also …
> fixed: enable once protection for Enketo at subpath

- public/js/src/module/settings.js
- test/client/utils.spec.js
- test/server/api-controller.spec.js
Remove the double call to `decodeURIComponent` and add some tests for encoding of `defaults` at the API endpoint.
closes #272
> Fix `d` query parameter decoding twice

- .eslintrc.json
- app/models/record-model.js
- app/models/survey-model.js
- jsdoc.config.js
- package-lock.json
- package.json
- public/js/src/enketo-webform-edit.js
- public/js/src/enketo-webform.js
- public/js/src/module/connection.js
- public/js/src/module/controller-webform.js
- public/js/src/module/encryptor.js
- public/js/src/module/form-cache.js
- public/js/src/module/records-queue.js
- public/js/src/module/store.js
- test/client/connection.spec.js
- test/client/encryptor.spec.js
- test/client/feature/last-saved.spec.js
- test/client/feature/survey-encryption.spec.js
- test/client/form-cache.spec.js
- test/client/records-queue.spec.js
- test/client/store.spec.js
Addresses #137.
Moving my progress checklist over here since #258 will only address a subset of this issue.
I'll add some additional notes/details inline once the PR is opened.
> Support for jr:instance/last-saved endpoint

- public/js/src/module/connection.js
- public/js/src/module/form-cache.js
- test/client/feature/last-saved.spec.js
- test/client/form-cache.spec.js
Fixes #279.
This introduces two changes to fix a regression introduced in #269:
- The store is bypassed in initialization when a form is previewed. As noted in a code comment, this was implemented in form-cache.js primarily to enable testing, but likely more appropriate in enketo-webform.js
- `getFormParts` now only calls `getLastSavedRecord` when `settings.type` is `other`, which is the default value when filling a form (versus `preview`, `single`, `edit`, `view`)
> Fixed: Form preview fails with IDBObjectStore error

- test/client/config/karma.conf.js
Before this change, source modules would only be recompiled when the *test* was saved. Note, `enketo-offline-fallback.js` is excluded because it's incomplete ([relevant previous discussion](https://github.com/enketo/enketo-express/pull/261#discussion_r638252258)).
> Ensure source files are recompiled in test watch mode

- .github/workflows/ghrc.yml
As noted at https://github.com/enketo/enketo-express/issues/312, we'd like to have PRs build images that QA can test. Unfortunately, building Docker images on PRs is not possible through a personal access token because secrets, understandably, are not passed to forks.
So instead, we build on every push. The idea here is that if we need to QA a PR, we can take those commits and push it to a branch and have QA test that. Maintainers can also manually push local builds to Github Packages if necessary.
> Build on every push to a branch, but not on PRs

- .eslintrc.json
- public/js/src/module/connection.js
- test/client/.eslintrc.json
- test/client/connection.spec.js
This fixes an issue introduced between [this change](https://github.com/enketo/enketo-express/pull/293/commits/577df16adad277184a7cadbd775a9a542d4e3d3f#diff-acb5beecd107235cca07564ab0a757e51a63149dfa40569bb8f58bb7a4a99a31R393) and [this commit](https://github.com/enketo/enketo-express/pull/293/commits/62943a2459cbf862a6261c6757b34c6cff4dc503) in #293, where once again display of binary defaults was broken. This is a minor change to remove behavior which changed a survey's `model` to use absolute URLs rather than the URLs originally provided to the transformer in the `media` mapping.
The bulk of the rest of this PR is backfilling tests for `getFormParts`. I thought that was more thoroughly tested (and there may be some redundancy with `last-saved.spec.js`), but I didn't feel comfortable …
> Fix: rendering of binary defaults in online-only mode

- app/controllers/transformation-controller.js
- app/lib/url.js
- public/js/src/module/file-manager.js
- test/client/file-manager.spec.js
- test/server/transformation-controller.spec.js
- test/server/url.spec.js
Closes #356
- ~~[ ] None of the above~~
- Loaded a form with binary defaults in a public access link (logged out, in Incognito mode) to verify that the media loads with the form's dynamic public access token.
- Validated that transformer escapes the same special HTML/XML characters with the same entities
- Validated that spaces and other special URL characters continue to be escaped and mapped as expected
This is a slightly safer (escaping reserved HTML/XML entities, still handles spaces and other URL characters that need to be escaped) version of the previous solution, before #291 and was determined to be the lowest risk short-term solution. Other solutions considered:
- Dynamically map media in the frontend DOM on load. This turned out to be unexpectedly complex.
- Transform for each …
> Fix: ensure dynamic manifest URLs are mapped

- app/lib/url.js
- test/server/transformation-controller.spec.js
Closes enketo/enketo-core#850.
Tests for both presence of form_logo.png and escaping its base path.
This was a regression in #360, which incorrectly restored the original escaping logic that was removed in #291. That logic previously mutated the `survey` parameter, when restoring it I intended to return a new `survey` object but missed this particular one.
I can not foresee any risk from this change that wasn't already a risk in #360 or #291.
See the attachment on enketo/enketo-core#850.
> Fix: ensure form_logo.png is included when present in media mapping

- .github/workflows/ghrc.yml
Closes #
~~- [ ] Online form submission~~
~~- [ ] Offline form submission~~
~~- [ ] Saving offline drafts~~
~~- [ ] Submitting offline drafts~~
~~- [ ] Editing submissions~~
~~- [ ] Form preview~~
~~- [ ] None of the above~~
I originally committed with a `cat .tag.txt` to validate that it does populate the file as expected.
It's probably not, but if we _do_ have git context within the Docker image we should probably remove that.
It will display the deployed commit hash when building an untagged version.
N/A
> Fix: use commit hash as version fallback when git tag is not available

- public/js/src/module/controller-webform.js
Closes #339.
The details of the bug are described in more depth [here](https://github.com/enketo/enketo-express/issues/339#issuecomment-953370459).
I'm really not sure what the actual name of this solution should be (please feel free to bikeshed it), but this is how it works:
1. Autosave is delayed by 500ms to work around #174
2. That delay is now wrapped with a `Promise`, which acts as a lock, blocking the request to `getCurrentFiles` when saving an offline record, ensuring signatures are auto-saved before the record is saved
3. As a matter of extra caution, multiple calls to `delay` only execute the last call if prior timers _have not completed_
4. Also as a matter of extra caution, multiple calls to `delay` where prior timers _have completed_ block `wait` until they _all resolve_.
- …
> Fix: not all signature images are uploaded in offline-capable forms

- config/default-config.json
- config/express.js
- tutorials/10-configure.md
Closes #399
Adds optional configuration values
```
"hsts": {
"include subdomains": false,
"preload": false,
"seconds": 100000
},
"csp": {
"enabled": true
"report only": true,
"value": "some optional custom header value"
},
```
These values are safe to omit.
-   [x] Submitting offline drafts
-   [x] Form preview
The default behavior, based on config, is to add only already documented security headers. Presumably those are safe as they are already recommended. 
IMO a tool such as [helmet](https://github.com/helmetjs/helmet) is more robust and less code for us to maintain, however it was recommended to avoid adding packages. Which sounds …
> Add configurable security headers

- app/models/config-model.js
- config/default-config.json
- public/js/src/module/connection.js
- tutorials/10-configure.md
Closes #418
-   [X] Online form submission
Submitted form data to kc.kobotoolbox.org
See issue
This is not a breaking change because the default config retains the __csrf cookie name, which is what most users will likely want 
A simple test is to change the cookie name and view it in the browser.
The ultimate test would be to deploy two ee instances to the same subdomain like ee1.example.com and ee2.example.com along with kobocat such as kc1.example.com and kc2.example.com. Without adjusting the domain, it should conflict. After adjusting changing the name of one, it should work. It can be tested by editing a form in …
> Allow client csrf cookie name to be configurable

- locales/src/en/translation.json
- public/js/src/module/connection.js
There is an edge condition that shows an unhelpful error message. I can be reproduced by:
1. loading an offline-capable form view, e.g. http://localhost:8005/x/widgets
2. turn off the Enketo server or go offline
3. remove the indexedDb database, e.g. by clicking the button that's hidden behind the version string in the sidebar
4. note the error message
I verified that any formserver-removed forms still show the existing, different and helpful custom message ("This form has been removed or deactivated etc.")
This seemed to me the only way to do this without interfering with other error messages.
In situations where the cached Enketo app fails to download a form, when it is offline (and in some other cases perhaps). The error message shown is "Failed to fetch".
This PR changes that into a …
> Show a less cryptic error message when form loading fails whilst offline

- app.js
- config/default-config.json
- tutorials/10-configure.md
Closes #372
-   [x] None of the above
Run application with and without max processes config value specified. Observe console output. I also tested setting it to a string. `"2"` will be interpreted as `2`.
A default of 16 IMO is too high, but it should be safer for legacy purposes. Users who expect a very high process count will only be affected when running on >16 core machines.
Potential (if unlikely) breaking change. A user who expects a very high amount of processes should set the `max processes` config value after updating.
This should benefit developers, who may want to set this to just 1 so as to save on startup …
> Add max processes config value

- locales/src/en/translation.json
- public/js/src/module/controller-webform.js
- public/js/src/module/store.js
…than 1 form with the same title exist in the local database, closes #416
Closes #416 
-   [x] Loading offline drafts
Options that were considered:
1 add another postfix (random string 2 or 3 characters) to record name
2 like previous but add the Enketo ID itself as the postfix or prefix (and hide it from the user in the form list?)
3 change database schema to no longer require record name to be unique (we haven't updated a database schema before, might be complicated)
4 like previous but roll our own uniqueness check that only looks at records under the same Enketo ID
5 change database schema to require uniqueness of …
> For offline-capable views, require unique record name + enketo ID and prompt users to edit record name in case of collision

- locales/src/en/translation.json
- public/js/src/module/connection.js
…ow useful error messages
Closes #422
For discussion: 
Would it be best to just treat previews the same as non-previews wrt missing external data? This would mean showing a helpful error message for each missing instance (as well any other loading errors). This PR assumes so, but I am happy to change that and show a single error message, and cease form loading for non-previews (e.g. referencing just the first missing instance or a generic "Can't find external data").
One argument for not making the distinction between previews and non-previews is that a form may pass preview testing (e.g. using a `form` query parameter) perfectly but the administrator forgets to attach external data files when launching it (e.g. in a different account).
Fwiw, OpenClinica makes a (simple) distinction …
> Use a more helpful error message if external data is missing in non-preview views

- public/js/src/module/gui.js
- test/client/gui.spec.js
Closes #439 
Manual verification.
It's probably not a great solution. This works around the behavior of the vex dialog library, and the underlying domify library. When called with a plain string, it appends the string to the DOM which automatically escapes it. By wrapping in a span tag, it inserts as raw HTML.
It's a potential XSS vulnerability, but the intent of the code prior to this change was to allow for that.
See #439
> Fix: don't escape HTML entities in alert dialogs

- CHANGELOG.md
- package-lock.json
- package.json
Don't know why package-lock had sha1s, they should be 512s. Hopefully this will be one-time noise and then they can stay 512s.
> Prepare for v4.1.1

- app/lib/context.js
Closes #443. Thanks to @noliveleger for filing the issue and identifying the root cause!
-   [x] Loading offline drafts
-   [x] Form preview
1. Set the local dev environment to use the Node flag `--expose-gc`.
2. Added `setInterval(() => gc(), 1000)` for consistent observation of memory usage before/after the change.
3. Created a local API endpoint which does nothing other than reference `getCurrentRequest` during a request/response cycle.
4. Send a bunch of `fetch` requests to that endpoint every ~200ms.
6. Watch memory usage steadily grow with the current implementation (about 1 MB every few seconds).
7. Watch memory usage plateau[^1] with …
> Fix: memory leak with async_hooks request context

- public/js/src/module/connection.js
We had a hardcoded absolute max file size of 100 MB that would overwrite a higher value that a form server says it can handle (by returning an `X-OpenRosa-Accept-Content-Length` header). E.g. if a form server says it can handle 150 MB, Enketo would ignore this and only allow 100 MB per file. OpenClinica would like to be able to increase file uploads to more than 100 MB.
There are three cases to consider:
A. A form/data server linked to its own Enketo server does not return an `X-OpenRosa-Accept-Content-Length` header. File uploads will continue to be limited to the default of 5 MB as they were before.
B. A form/data server linked to its own Enketo server returns an `X-OpenRosa-Accept-Content-Length` header. In that case that server probably has good reasons for using that value. 
C. An …
> removed: absolute maximum size for file uploads

- app/controllers/submission-controller.js
- test/server/submission-controller.spec.js
This ensures that Enketo does not attempt to stream unexpected submission request bodies to an OpenRosa server.
-   [x] Loading offline drafts
-   ~~[ ] Form preview~~ Not applicable
Manual and automated tests. I also verified that this is the same response an OpenRosa server would send for the same invalid payloads.
Non-multipart POST bodies are invalid for submissions.
This should have no user impact.
N/A
> Fix: fail early on non-multipart submissions

- .eslintrc.json
- .gitignore
- tools/redis-repl
Sharing in case it's interesting: a little tool I built to help explore the contents of the redis store that enketo-express connects to.
Example session:
```javascript
$ ./tools/redis-repl 
[redis-repl] Connecting to redis at 127.0.0.1:6379...
[redis-repl] Connected.
node-redis docs: https://github.com/redis/node-redis/tree/v3.1.2#usage
Available globals:
client          Redis client.
listKeys()      Show all keys in the database.
await get(key)  Get something from the database.
describe(key)   Get something from the database.
help()          Show this message.
redis> describe('su:2jCCSuaf')
key: su:<enketo-id>     value: Submission IDs
undefined
redis> await get('su:2jCCSuaf')
redis> [
'uuid:3b0d7bce-eff1-472d-8e6a-c3e2be51d9a4',
'uuid:388d1107-d87c-4bcf-90b7-f622d4532458', …
```
> Add redis-repl tool

- public/js/src/enketo-webform-view.js
Fixes #481.
-   Online form submission
-   Offline form submission
-   Saving offline drafts
-   Loading offline drafts
-   Editing submissions
-   Form preview
-   None of the above
Temporarily added a `/view/:enketo_id` route (because I don't know/can't remember how to access view mode with an encrypted id), loaded a form to reproduce the error, then manually validated that the change eliminates that error.
This property is now required in the call to controller-webform.js's `init`.
No regression risk I can imagine, this fixes a regression in #459.
You'd need to know how to access a form in view mode.
> Fix: ensure `survey.media` is available in view mode

- Dockerfile
> This command is similar to npm install, except it's meant to be used
> in automated environments such as test platforms, continuous
> integration, and deployment -- or any situation where you want to
> make sure you're doing a clean install of your dependencies.
>
> - https://docs.npmjs.com/cli/v8/commands/npm-ci/
> Dockerfile: use npm ci

- config/default-config.json
- package-lock.json
- package.json
- public/js/src/module/core-widgets.json
Folks who explicitly configure widgets in their config will have to be really careful to add these widgets.
- **NOTE** invalid values are cleared at this point which could lead to data loss. But I think it's ok to expect users to fix big red validation issues.
-   [x] Loading offline drafts
-   [x] Form preview
Tried various inputs in Firefox which was the source of issues previously.
It's applying the patch from the latest Core release.
There is some level of risk to numeric inputs which are pretty critical. ODK will do a QA pass at some point but others may want to verify this carefully as well.
As noted above, folks who explicitly configure …
> Add number widgets by default

- CHANGELOG.md
- docs/app_controllers_transformation-controller.js.html
- docs/module-transformation-controller.html
- package-lock.json
- package.json
Prepares release 5.0.0.
This is not a great sequence of releases. I want to provide a little bit of context for anyone watching and/or myself later.
It seemed simple and sensible to use the Enketo Core widgets framework to improve numeric inputs (https://github.com/enketo/enketo-core/pull/926). For some reason I thought everything worked in Express when I updated Core in https://github.com/enketo/enketo-express/releases/tag/4.1.5. 
I quickly realized that Core widgets are not included by default by Express which to me is surprising. I can see how someone might want to map to custom widgets, though.
That left us with Core released with new integer and decimal widgets and EE not using them at all. I wasn't able to work through what to do immediately so I marked the releases as unusable …
> Prepare 5.0.0 release

- .gitignore
- Gruntfile.js
- app/views/styles/component/_form_header.scss
- app/views/styles/component/_variables.scss
Also eliminates the system-sass-variables build step
Closes https://github.com/getodk/central/issues/370
-   No other modes are applicable
Checked that the image loads as expected with the default Central base path, as well as a modified base path of `/enk/eto` to verify it works at arbitrary path depth.
Less code and fewer build steps to accomplish the same thing. This specifically affects Docker, which don't (and shouldn't) have a local config when we publish the image. An alternative approach would be to use the standard [`base`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) element, but that would affect quite a few other relative URLs already in use. I'd like to make that change, but felt it's better to do in a future change not …
> Fix: loading offline-enabled.png regardless of base path

- public/js/src/module/connection.js
Fixes: https://github.com/enketo/enketo-express/issues/518
-   [x] Form preview
> fix: load external data when served with 'application/geo+json' Content-Type header

- setup/docker/start.sh
Closes #531
Start via Docker Compose (I choose to mount the start.sh file inside the Docker image `kobotoolbox/enketo-express-extra-widgets` for convenience. Without this patch, the following scenarios are not handled properly and only the 10 second docker termination timeout will stop the container.
- (exec in docker container) kill 1
- Terminate docker compose via Ctrl-C interrupt
- Terminate docker container via `docker stop`
With this patch, the container exists almost immediately (under 1 second).
Additionally, I tested in a Kubernetes cluster by overriding the command with pm2-runtime. …
> Use pm2-runtime on docker/start.sh

- app/controllers/media-controller.js
- app/lib/communicator.js
- app/models/cache-model.js
- app/models/survey-model.js
- config/express.js
- tutorials/00-getting-started.md
This namespaces all `debug` statements so its easier to enable _only_ enketo logs. 
Tested locally, and on a custom docker build
Its really difficult currently to see all debug logs for enketo only. Sure, we can set `DEBUG=*` but that gives us way too many logs from other modules that use `debug`. 
setting `DEBUG=enketo*` gives us more specificity. 
Shouldn't affect end users, only administrators if they currently have the `DEBUG` variable set. 
No
> feat(app): add enketo namespace to all debug statements

- public/js/src/module/geojson.js
- test/client/feature/geojson-external-instance.spec.js
- test/fixtures/geojson/feature-collection-with-unsupported-type.geojson
- test/fixtures/geojson/feature-collection.geojson
Closes #553.
This is largely based on https://github.com/getodk/javarosa/pull/707. The biggest divergence besides obvious language/API differences is the validation approach. And `@ts-check` was added to ensure the validation and types actually match the expected runtime values.
Added tests, though some from the JavaRosa change were skipped as they felt redundant.
-
I think the risk of regression is low unless there's some mistake where the change touches existing code.
A suitable test form is attached to #553
> Add support for LineString and Polygon GeoJSON types

- app/lib/pdf.js
Currently puppeteer's `pdf` function is not used with a timeout. OpenClinica has run into issues with long forms timing out before the `pdf` function completed (probably due to hitting an internal default timeout). The solution is to make this configurable. I think the already present config item `headless.timeout` can be used for this.
https://pptr.dev/api/puppeteer.pdfoptions
-   [x] PDF API endpoints
nothing
A new separate configuration item was considered but deemed unnecessary.
The default headless.timeout in default-config.json that will now be used is 300 seconds. OpenClinica was hitting a 30 second (mysterious) timeout before this change. So, I don't think there is a significant chance of regressions for users.
No specific form needed. PDF generation can be tested with e.g. …
> Make pdf generation timeout configurable

- Dockerfile
-   [x] None of the above
It builds, and appears to run (at least to the predictable point of failing to connect to Redis, which I believe is out of scope for this). The NPM version needed to be made explicit for build to succeed.
It's not. We should reevaluate what is an appropriate base image, and more explicitly manage dependencies and their versions—ideally at the project level, but at least in a consistent way (e.g. Volta for Node version management). And we should eliminate unneeded dependencies (e.g. Python).
The Docker image is using a different minor version of Node and NPM than the project, which could be a …
> Update Docker base image to Node 16

- Dockerfile
`pm2-runtime` will now run as PID 1 as intended in #533. See also https://github.com/enketo/enketo-express/issues/531#issuecomment-1633255721.
-   [x] None of the above
(…because no application code has changed. If anyone feels they're warranted, however, I'm happy to carry out the tests.)
Verified `pm2-runtime` as PID 1 within the container using the following method:
```
john@world$ git show --oneline --no-patch
9f4d9aa0 (HEAD -> override-docker-entrypoint, origin/override-docker-entrypoint) Override Docker ENTRYPOINT so that PID 1 inside…
john@world$ docker build -t ee-test-entrypoint .
<snip>
Successfully tagged …
```
> Override Docker ENTRYPOINT so that PID 1 inside the container is correctly assigned

- Dockerfile
When run with downstream images [such as ODK Central's](https://github.com/getodk/central/blob/master/enketo.dockerfile), the `ENTRYPOINT` change (#571) results in 404 responses from the transformation API endpoint. As we're preparing a release (#581), we're temporarily rolling back that change so we can investigate further.
> Revert "Override Docker ENTRYPOINT…"
