- setup/docker/01_setup_enketo.bash
- setup/docker/docker-compose.yml
Moved files used to compare asset build to one folder. 
This folder can be mapped to docker volume. It can persist even if the container is removed.
> Persist check files on disk

- setup/docker/01_setup_enketo.bash
- setup/docker/docker-compose.yml
As suggested by @jnm, quick change to handle `sha1sum` errors.
> Better handling of errors on grunt build checks

- public/js/src/module/file-manager.js
https://github.com/enketo/enketo-express/issues/103
> Add support for max-pixels in file upload widget

- public/js/src/module/connection.js
Fixes: https://github.com/enketo/enketo-express/issues/241
> Fix typo: Change error.msg -> error.message

- app/views/surveys/webform-redirect.pug
I propose to test if the pathname endWith insteed of === in case of enketo is not on the root path url (e.i. mydomain.com/enketo/x/#abcde)
Fixes #213
> [#213] pathname with a base root url

- public/js/src/module/controller-webform.js
Fixes #296. This change ensures the store is not accessed to update a form's external last-saved instances unless the form will be reset.
> Fix: do not display error when submitting an edit

- CHANGELOG.md
- docs/tutorial-30-develop.html
- jsdoc.config.js
- package.json
I did the following....
* bumped the version in package.json
* `npm run beautify`
* `npm run build-docs`
`npm run test` is failing, which is why this a draft. It might be specific to my computer, so if the tests pass in CI, we can merge.
> Prepare for 2.8.1

- CHANGELOG.md
- docs/index.html
- package-lock.json
- package.json
- tutorials/30-develop.md
Only issue was `npm run test` was failing due to redis not being installed.
> Prepare for 3.0.0

- CHANGELOG.md
- docs/tutorial-30-develop.html
- package.json
I ran the following:
- Make sure tests pass: `npm run test`
- Beautiful code: `npm run beautify`
- Build documentation: `npm run build-docs`
Since this is not a major release, I did not do an `npm update|audit`
> Prepare for 3.0.1

- app/lib/communicator/communicator.js
- test/server/communicator-lib.spec.js
Fixing https://github.com/enketo/enketo-express/pull/340 which I accidentally closed/deleted.
**We will wait for 24 hours for QA to review some other changes before this added to master!**
> Fix: unescaped form ID when requesting form list

- locales/src/en/translation.json
I find the wording here hard to parse, so I'd suggest this.
> Clearer recommendation phrasing

- tutorials/10-configure.md
Closes #308 
Updates the docs to reflect that query parameters meanwhile work with offline forms, too. Also added note for potential security risks related to external token authentication, as discussed in the ticket.
/
/
/
/
> Fix docs: Query parameters working in offline forms

- .eslintrc.json
- app/models/survey-model.js
- public/js/src/enketo-webform.js
- public/js/src/module/connection.js
- public/js/src/module/last-saved.js
- test/client/connection.spec.js
- test/client/feature/last-saved.spec.js
Addresses #363 but I'm not sure this is sufficient to close it, for a few reasons:
1. Currently this only addresses both preview cases. In the linked issue, @MartijnR says the intent is to:
> show external file errors together with any form load errors, but still show the form (and disable submissions)
Which seems to suggest this change should also address non-preview modes, but the change associated with that comment specifically special-cases preview mode, so I'm unclear about the intent. (This is why I'm also initially opening this as a draft.)
2. The error messages are _better_, but maybe not great? But those errors are now coming from enketo-core, so further improvement will likely need to happen there.
-   [x] Saving …
> Improve errors for missing external instances in preview mode

- app/views/styles/component/_side-slider.scss
- app/views/surveys/component/_side-slider.pug
- locales/src/en/translation.json
- public/js/src/module/controller-webform.js
- public/js/src/module/records-queue.js
… online with a queue ready to send, closes #43
Also fixes a bug where the upload button gets re-enabled after a user saves another record record whilst offline.
Closes #410
-   [ ] Submitting offline drafts - ?? (this is not a supported feature)
> Don't disable the upload button so much

- CHANGELOG.md
- Dockerfile
- package-lock.json
- package.json
Restores the build step in Dockerfile
> Prepare to release 4.0.1

- CHANGELOG.md
issue matches similar issue in enketo-core: https://github.com/enketo/enketo-core/issues/856
> Added missing item to changelog for version 3.0.2

- test/server/config-model.spec.js
Closes #428
-   [x] None of the above (N/A)
> Fix (test): ensure config-model tests are properly isolated

- public/js/src/module/records-queue.js
> Fixed: upload button gets enabled before queue is empty, closes #432

- README.md
Briefly updates the project status. Goals are:
- keep us focused on our goals
- give us something to point to when we say a particular issue or PR is not currently a priority
- provide some visibility into our process for folks who would like to participate
I considered writing some things about longer-term goals but I think this is sufficiently useful for now.
> Describe project status

- tutorials/10-configure.md
Follow up to https://github.com/enketo/enketo-express/pull/503 and https://github.com/enketo/enketo-express/pull/496
> Docs: changes to base path don't require rebuild, widgets warnings

- public/js/src/module/utils.js
- test/client/utils.spec.js
Closes #488.
-   [X] None of the above
I'll manually validate if requested, but I think the tests should be sufficient.
I thought about looking into using another CSV parser, but that has its own set of regression risks.
It's possible there is some valid or invalid case I haven't considered/tested.
N/A
> Fix: single-column CSV

- public/js/src/module/utils.js
- test/client/utils.spec.js
Closes #529.
-   [x] None of the above
I think the tests are sufficient validation, but I'm happy to run it if preferred.
Several tests. Not exhaustive, but go a bit beyond the issue as the change is broader.
The XML specification explicitly defines a grammar for names.
It's possible the character ranges defined in the spec are more permissive than we want, but if that's the case it would also be true for our use of native APIs like `DOMParser`.
> Fix: validate CSV header names according to XML spec

- locales/src/sk/translation.json
Not sure if you have a better way to update translations, so let me know if you don't have much use for these PRs whenever I happen to notice a change. Historically, I updated these whenever I noticed a change in Transifex (or got an alert), so I wouldn't forget.
> changed: updated Slovak translation

- package-lock.json
- package.json
Uses https://github.com/enketo/enketo-core/commit/425eabdc72c7040b521dc324c346ff22d85031aa as described in https://github.com/enketo/enketo-core/pull/976#issuecomment-1558526315.
> Use Core version with performance optimizations
